openapi: 3.0.0
info:
  title: Car API
  version: 1.0.0
  description: Simple API to manage cars
servers:
  - url: http://localhost:3000
    description: Local server  #  наш тестовый сервер
tags:
  - name: car
    description: Operations about cars  #  группируем все методы по машинам
paths:
  /cars:
    get:
      tags:
        - car
      summary: Get all cars  #  получаем список всех машин
      responses:
        '200':
          description: List of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'  #  возвращаем массив Car
    post:
      tags:
        - car
      summary: Add a new car  # добавляем новую машину
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'  # принимаем объект Car
      responses:
        '201':
          description: Car created  # 201 для успешного создания
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'

  /cars/{carId}:
    get:
      tags:
        - car
      summary: Get a car by ID  # получаем одну машину по ID
      parameters:
        - name: carId
          in: path
          required: true
          schema:
            type: integer  # ID должен быть числом
      responses:
        '200':
          description: Car found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: Car not found  # ← если машины нет
    put:
      tags:
        - car
      summary: Replace a car by ID  # полная замена машины
      parameters:
        - name: carId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          description: Car replaced
    patch:
      tags:
        - car
      summary: Update a car by ID  # частичное обновление
      parameters:
        - name: carId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        '200':
          description: Car updated
    delete:
      tags:
        - car
      summary: Delete a car by ID  # удаляем машину
      parameters:
        - name: carId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Car deleted  # 204 = нет содержимого после удаления

components:
  schemas:
    Car:
      type: object
      required:
        - ID
        - VIN
        - GOS_number
        - mark
        - model
        - year
        - user_ID  # все эти поля обязательные!
      properties:
        ID:
          type: integer
          example: 1  # пример для тестов
        VIN:
          type: string
          example: "X12345ABC67890YZ"  # VIN номер
        GOS_number:
          type: string
          example: "A123BC77"  # гос. номер
        mark:
          type: string
          example: "Toyota"  # марка машины
        model:
          type: string
          example: "Camry"  # модель
        year:
          type: integer
          example: 2021  # год выпуска
        user_ID:
          type: integer
          example: 101  # ID владельца
